priorities:
  bypass:
    permission: queue.priority.bypass
    weight: 999
  premium:
    permission: queue.priority.premium
    weight: 1
  hero:
    permission: queue.priority.hero
    weight: 2
  master:
    permission: queue.priority.master
    weight: 3


# This is the sign players see when they aren't in the queue.
queue-sign:
  line1: "%server% QueuePlugin"
  line2: "&a%online%&f/&a%limit%"
  line3: "&dClick to join"
  line4: "&dthe queue!"

# This is the sign that shows how many of each rank is in the queue.
info-sign:
  line1: "QueuePlugin Info"
  line2: "Rank1: %rank1%"
  line3: "Rank2: %rank2%"
  line4: "Rank3: %rank3%"

# This is the message you will be shown if you right click an info sign
info-sign-message: "&dYou can donate for higher queue priority at &ewww.yourshop.com&d!"

queue-sign-locations: {}
info-sign-locations: {}